# GUESSING GAME
""" In this game user has to guess the number which is secret number generated by computer within certain range,
       for every guess computer will provide feedback about your guess """

import random


def guess(x):
    random_number = random.randint(1, x)
    guess = 0
    while guess != random_number:
        guess = int(input(f"Guess a number between 1 and {x}: "))
        if guess < random_number:
            print("Sorry,Too low, Guess again.")
        elif guess > random_number:
            print("Sorry,Too high, Guess again.")

    print(f"Congratulations, You have guessed the number right. The number is {random_number}")


if __name__ == '__main__':
    print("WELCOME to NUMBER GUESSING GAME\n")
    guess(50)